DEBUG 14229: GitBook plugins:
gitbook-plugin-edit-link
gitbook-plugin-forkmegithub-cn
gitbook-plugin-search-plus
gitbook-plugin-sharing-plus
gitbook-plugin-anchor-navigation-ex
gitbook-plugin-github-buttons@2.1.0
gitbook-plugin-splitter
gitbook-plugin-image-captions-extended
gitbook-plugin-bsz
gitbook-plugin-fancybox
gitbook-plugin-katex
gitbook-plugin-image-wrapper
gitbook-plugin-gtalk

DEBUG 14229: npm arguments:  
install
--no-save
gitbook-plugin-edit-link
gitbook-plugin-forkmegithub-cn
gitbook-plugin-search-plus
gitbook-plugin-sharing-plus
gitbook-plugin-anchor-navigation-ex
gitbook-plugin-github-buttons@2.1.0
gitbook-plugin-splitter
gitbook-plugin-image-captions-extended
gitbook-plugin-bsz
gitbook-plugin-fancybox
gitbook-plugin-katex
gitbook-plugin-image-wrapper
gitbook-plugin-gtalk
--registry=https://registry.npm.taobao.org

